# Right now we will only spin up keycloak
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

    ports:
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:9443:8443"
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./import:/opt/keycloak/data/import 
    command: start-dev --import-realm